Repository Rythe-Interactive/Rythe-Engine, pull requests merged in 2020-12, with the labels that each got.

#205 LAP 63 mesh data rework
  applications/sandbox/assets/scenes/Main.cornflake
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystem.hpp
  include/rendering/components/particle.hpp
  include/rendering/components/particle_emitter.hpp
  include/rendering/data/particle_system_base.hpp
  include/rendering/data/particle_system_cache.hpp
  include/rendering/systems/particle_system_manager.hpp
  legion/engine/core/defaults/coremodule.hpp
  legion/engine/core/defaults/defaultcomponents.hpp
  legion/engine/core/ecs/archetype.hpp
  legion/engine/core/ecs/ecsregistry.hpp
  legion/engine/rendering/components/renderable.hpp
  legion/engine/rendering/data/model.cpp
  legion/engine/rendering/data/model.hpp
  legion/engine/rendering/data/particle_system_base.cpp
  legion/engine/rendering/module/renderingmodule.hpp
  legion/engine/rendering/systems/renderer.hpp
  xcopyexclude
Labels: enhancement, team core, team rendering

#222 hotfix/query-safety
  applications/sandbox/systems/testsystem.hpp
  include/rendering/components/particle.hpp
  include/rendering/components/particle_emitter.hpp
  include/rendering/data/particle_system_base.hpp
  include/rendering/data/particle_system_cache.hpp
  include/rendering/systems/particle_system_manager.hpp
  legion/engine/application/window/windowsystem.cpp
  legion/engine/audio/systems/audiosystem.inl
  legion/engine/core/ecs/entityquery.cpp
  legion/engine/core/ecs/entityquery.hpp
  legion/engine/core/ecs/queryregistry.cpp
  legion/engine/core/ecs/queryregistry.hpp
  legion/engine/physics/systems/physicssystem.hpp
  legion/engine/rendering/systems/particle_system_manager.hpp
  legion/engine/rendering/systems/renderer.hpp
Labels: HIGH PRIORITY, bug

#221 Minor fix particle system
  applications/sandbox/systems/pointcloud_particlesystem.hpp
  legion/engine/rendering/components/particle.hpp
  legion/engine/rendering/data/particle_system_base.hpp
  legion/engine/rendering/data/particle_system_cache.cpp
  legion/engine/rendering/data/particle_system_cache.hpp
  legion/engine/rendering/systems/particle_system_manager.hpp
Labels: bug

#223 spinlock critical section
  legion/engine/core/async/readonly_rw_spinlock.hpp
  legion/engine/core/ecs/ecsregistry.hpp
Labels: enhancement

#224 feature/window-size
  legion/engine/application/window/window.hpp
  legion/engine/application/window/windowsystem.cpp
  legion/engine/core/logging/logging.hpp
Labels: enhancement

#219 [LAP-19] more physics integration
  applications/sandbox/systems/testsystem.hpp
  docs/source/application-wiki/application-index.rst
  docs/source/architecture-wiki/architecture-index.rst
  docs/source/architecture-wiki/eventbus.rst
  docs/source/architecture-wiki/result.rst
  docs/source/fs-wiki/advanced_file_system_usage.rst
  docs/source/fs-wiki/asset_import_pipelines.rst
  docs/source/fs-wiki/automatic_conversion.rst
  docs/source/fs-wiki/custom_providers.rst
  docs/source/fs-wiki/fs-index.rst
  docs/source/fs-wiki/virtual_filesystems.rst
  docs/source/getting-started.rst
  docs/source/index.rst
  docs/source/legiontheme/__pycache__/__init__.cpython-37.pyc
  docs/source/legiontheme/nameko/static/pygments.css
  docs/source/physics-wiki/physics-index.rst
  legion/engine/core/filesystem/resource.hpp
  legion/engine/physics/colliders/physicscollider.hpp
  legion/engine/physics/events/events.hpp
  legion/engine/physics/events/trigger_event.hpp
  legion/engine/physics/physics.vcxproj
  legion/engine/physics/physics.vcxproj.filters
  legion/engine/physics/systems/physicssystem.hpp
Labels: documentation, enhancement

#226 low power enforcing when not enough threads can be found
  applications/sandbox/systems/simplecameracontroller.hpp
  legion/engine/core/scheduling/scheduler.cpp
Labels: enhancement

#228 Lap-47-3D-Voronoi
  applications/sandbox/assets/vec.txt
  applications/sandbox/assets/voronoi/output/cells.json
  applications/sandbox/assets/voronoi/presetpoints/pack_ten_cube
  applications/sandbox/assets/voronoi/presetpoints/pack_torus
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/systems/testsystem.hpp
  applications/sandbox/systems/testsystem2.hpp
  deps/include/Voro++/c_loops.hh
  deps/include/Voro++/cell.hh
  deps/include/Voro++/common.hh
  deps/include/Voro++/config.hh
  deps/include/Voro++/container.hh
  deps/include/Voro++/container_prd.hh
  deps/include/Voro++/pre_container.hh
  deps/include/Voro++/rad_option.hh
  deps/include/Voro++/unitcell.hh
  deps/include/Voro++/v_base.hh
  deps/include/Voro++/v_compute.hh
  deps/include/Voro++/voro++.hh
  deps/include/Voro++/wall.hh
  deps/include/Voro++/worklist.hh
  deps/lib/Voro++.lib
  legion/engine/core/math/glm/detail/type_vec4.hpp
  legion/engine/core/math/glm/detail/type_vec4.inl
  legion/engine/core/serialization/serializationUtil.hpp
  legion/engine/physics/physics_statics.hpp
Labels: enhancement

#233 added cloning functionality to entities
  applications/sandbox/assets/scenes/Main.cornflake
  applications/sandbox/systems/testsystem.hpp
  legion/engine/core/ecs/component_container.hpp
  legion/engine/core/ecs/ecsregistry.cpp
  legion/engine/core/ecs/ecsregistry.hpp
  legion/engine/core/ecs/entity_handle.cpp
  legion/engine/core/ecs/entity_handle.hpp
Labels: enhancement

#235 Fixed an issue that would crash OpenCl
  legion/engine/core/compute/kernel.cpp
  legion/engine/core/compute/kernel.hpp
Labels: bug

#242 [LAP 18] Explosion VFX
  applications/sandbox/assets/models/explosionMesh.mtl
  applications/sandbox/assets/models/explosionMesh.obj
  applications/sandbox/assets/models/particleModel.mtl
  applications/sandbox/assets/models/particleModel.obj
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/sandbox.vcxproj.filters
  applications/sandbox/systems/explosion_particlesystem.hpp
  applications/sandbox/systems/testsystem2.hpp
  legion/engine/rendering/components/particle_emitter.hpp
  legion/engine/rendering/data/particle_system_base.cpp
  legion/engine/rendering/data/particle_system_base.hpp
  legion/engine/rendering/systems/particle_system_manager.hpp
  legion/engine/rendering/systems/pointcloud_particlesystem.hpp
Labels: enhancement

#247 [LAP-82] added imgui
  applications/sandbox/imgui.ini
  applications/sandbox/module/testModule.hpp
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/sandbox.vcxproj.filters
  applications/sandbox/source.cpp
  applications/sandbox/systems/explosion_particlesystem.hpp
  applications/sandbox/systems/gui_test.hpp
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystem.hpp
  applications/sandbox/systems/testsystem2.hpp
  deps/include/imgui/Dirent/dirent.h
  deps/include/imgui/ImCurveEdit.h
  deps/include/imgui/ImGradient.h
  deps/include/imgui/ImGuiFileBrowser.h
  deps/include/imgui/ImGuizmo.h
  deps/include/imgui/ImSequencer.h
  deps/include/imgui/ImZoomSlider.h
  deps/include/imgui/LICENSE.txt
  deps/include/imgui/backends/imgui_impl_glfw.h
  deps/include/imgui/backends/imgui_impl_opengl3.h
  deps/include/imgui/imconfig.h
  deps/include/imgui/imfilebrowser-LICENSE.txt
  deps/include/imgui/imgui.h
  deps/include/imgui/imgui_internal.h
  deps/include/imgui/imguizmo-LICENSE.txt
  deps/include/imgui/imnodes-LICENSE.txt
  deps/include/imgui/imnodes.h
  deps/include/imgui/imstb_rectpack.h
  deps/include/imgui/imstb_textedit.h
  deps/include/imgui/imstb_truetype.h
  legion/engine/rendering/imgui_impl/ImCurveEdit.cpp
  legion/engine/rendering/imgui_impl/ImGradient.cpp
  legion/engine/rendering/imgui_impl/ImGuiFileBrowser.cpp
  legion/engine/rendering/imgui_impl/ImGuizmo.cpp
  legion/engine/rendering/imgui_impl/ImSequencer.cpp
  legion/engine/rendering/imgui_impl/imgui.cpp
  legion/engine/rendering/imgui_impl/imgui_demo.cpp
  legion/engine/rendering/imgui_impl/imgui_draw.cpp
  legion/engine/rendering/imgui_impl/imgui_impl_glfw.cpp
  legion/engine/rendering/imgui_impl/imgui_impl_opengl3.cpp
  legion/engine/rendering/imgui_impl/imgui_widgets.cpp
  legion/engine/rendering/imgui_impl/imnodes.cpp
  legion/engine/rendering/pipeline/gui/stages/imguirenderstage.cpp
  legion/engine/rendering/pipeline/gui/stages/imguirenderstage.hpp
  legion/engine/rendering/rendering.vcxproj
  legion/engine/rendering/rendering.vcxproj.filters
  legion/engine/rendering/util/gui.hpp
Labels: enhancement

#248 Feature/spinlock overhaul
  applications/sandbox/imgui.ini
  applications/sandbox/module/testModule.hpp
  applications/sandbox/systems/gui_test.hpp
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystem.hpp
  legion/engine/application/application.vcxproj
  legion/engine/application/application.vcxproj.filters
  legion/engine/application/context/contexthelper.cpp
  legion/engine/application/context/contexthelper.hpp
  legion/engine/application/window/window.cpp
  legion/engine/application/window/window.hpp
  legion/engine/application/window/windowsystem.cpp
  legion/engine/application/window/windowsystem.hpp
  legion/engine/audio/data/audio_segment.cpp
  legion/engine/audio/data/audio_segment.hpp
  legion/engine/audio/data/importers/audio_importers.cpp
  legion/engine/audio/systems/audiosystem.cpp
  legion/engine/audio/systems/audiosystem.hpp
  legion/engine/audio/systems/audiosystem.inl
  legion/engine/core/async/async.hpp
  legion/engine/core/async/readonly_rw_spinlock.cpp
  legion/engine/core/async/readonly_rw_spinlock.hpp
  legion/engine/core/async/ring_sync_lock.hpp
  legion/engine/core/async/rw_spinlock.cpp
  legion/engine/core/async/rw_spinlock.hpp
  legion/engine/core/async/spinlock.cpp
  legion/engine/core/async/spinlock.hpp
  legion/engine/core/async/transferable_atomic.hpp
  legion/engine/core/common/managed_resource.hpp
  legion/engine/core/containers/atomic_sparse_map.hpp
  legion/engine/core/containers/hashed_sparse_set.hpp
  legion/engine/core/containers/sparse_map.hpp
  legion/engine/core/core.vcxproj
  legion/engine/core/core.vcxproj.filters
  legion/engine/core/data/image.cpp
  legion/engine/core/data/image.hpp
  legion/engine/core/data/mesh.cpp
  legion/engine/core/data/mesh.hpp
  legion/engine/core/ecs/component_container.hpp
  legion/engine/core/ecs/ecsregistry.cpp
  legion/engine/core/ecs/ecsregistry.hpp
  legion/engine/core/ecs/entity_handle.cpp
  legion/engine/core/ecs/entity_handle.hpp
  legion/engine/core/ecs/queryregistry.hpp
  legion/engine/core/filesystem/artifact_cache.hpp
  legion/engine/core/platform/platform.hpp
  legion/engine/core/scheduling/processchain.cpp
  legion/engine/core/scheduling/processchain.hpp
  legion/engine/core/scheduling/scheduler.cpp
  legion/engine/core/scheduling/scheduler.hpp
  legion/engine/rendering/data/material.cpp
  legion/engine/rendering/data/material.hpp
  legion/engine/rendering/data/model.cpp
  legion/engine/rendering/data/model.hpp
  legion/engine/rendering/data/particle_system_cache.cpp
  legion/engine/rendering/data/particle_system_cache.hpp
  legion/engine/rendering/data/shader.cpp
  legion/engine/rendering/data/shader.hpp
  legion/engine/rendering/data/texture.cpp
  legion/engine/rendering/data/texture.hpp
Labels: enhancement

#249 [LAP-36] post processing
  applications/sandbox/assets/shaders/blurcolor.shs
  applications/sandbox/assets/shaders/edgedetection.shs
  applications/sandbox/assets/shaders/invertcolor.shs
  applications/sandbox/data/pp_blur.hpp
  applications/sandbox/data/pp_edgedetect.hpp
  applications/sandbox/engine/shaderlib/texturemaps.shinc
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/sandbox.vcxproj.filters
  applications/sandbox/systems/testsystem.hpp
  legion/engine/rendering/data/framebuffer.cpp
  legion/engine/rendering/data/framebuffer.hpp
  legion/engine/rendering/data/importers/texture_importers.cpp
  legion/engine/rendering/data/postprocessingeffect.cpp
  legion/engine/rendering/data/postprocessingeffect.hpp
  legion/engine/rendering/data/screen_quad.hpp
  legion/engine/rendering/data/shader.hpp
  legion/engine/rendering/data/texture.cpp
  legion/engine/rendering/data/texture.hpp
  legion/engine/rendering/pipeline/default/defaultpipeline.cpp
  legion/engine/rendering/pipeline/default/stages/postprocessingstage.cpp
  legion/engine/rendering/pipeline/default/stages/postprocessingstage.hpp
  legion/engine/rendering/pipeline/default/stages/submitstage.cpp
  legion/engine/rendering/rendering.vcxproj
  legion/engine/rendering/rendering.vcxproj.filters
  legion/engine/rendering/systems/oldrenderer.hpp
Labels: enhancement, team rendering

#252 Feature/post processing fix
  applications/sandbox/data/pp_blur.hpp
  applications/sandbox/data/pp_edgedetect.hpp
  legion/engine/rendering/data/postprocessingeffect.hpp
  legion/engine/rendering/pipeline/default/stages/postprocessingstage.cpp
Labels: enhancement

#255 [LAP-84] Feature/messy quick hull
  applications/sandbox/assets/models/convexhulltest_0.mtl
  applications/sandbox/assets/models/convexhulltest_0.obj
  applications/sandbox/module/testModule.hpp
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/sandbox.vcxproj.filters
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystem.hpp
  applications/sandbox/systems/testsystemconvexhull.hpp
  legion/engine/core/core.vcxproj
  legion/engine/core/core.vcxproj.filters
  legion/engine/core/math/close_enough.hpp
  legion/engine/core/math/color.hpp
  legion/engine/core/math/geometry.hpp
  legion/engine/core/math/math.hpp
  legion/engine/physics/HalfEdgeFace.cpp
  legion/engine/physics/colliders/convexcollider.cpp
  legion/engine/physics/colliders/convexcollider.hpp
  legion/engine/physics/components/physics_component.cpp
  legion/engine/physics/components/physics_component.hpp
  legion/engine/physics/data/convexconvexpenetrationquery.cpp
  legion/engine/physics/data/edgepenetrationquery.cpp
  legion/engine/physics/halfedgeedge.hpp
  legion/engine/physics/halfedgeface.hpp
  legion/engine/physics/physics_statics.hpp
Labels: enhancement

#258 fixed mesh renderable merge bug
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystemconvexhull.hpp
  legion/engine/core/core.vcxproj
  legion/engine/core/core.vcxproj.filters
Labels: bug

#257 Feature/thread safe render pipeline
  applications/sandbox/assets/shaders/pbr.shs
  applications/sandbox/assets/shaders/skybox.shs
  applications/sandbox/data/pp_blur.hpp
  applications/sandbox/data/pp_edgedetect.hpp
  applications/sandbox/engine/shaderlib/color_correction.shinc
  applications/sandbox/engine/shaderlib/lighting_input.shinc
  applications/sandbox/engine/shaderlib/stdio.shinc
  applications/sandbox/engine/shaderlib/texturemaps.shinc
  applications/sandbox/engine/shaders/aces.shs
  applications/sandbox/engine/shaders/invalid.shs
  applications/sandbox/engine/shaders/legiontonemap.shs
  applications/sandbox/engine/shaders/reinhard.shs
  applications/sandbox/engine/shaders/reinhardjodie.shs
  applications/sandbox/engine/shaders/screenshader.shs
  applications/sandbox/engine/shaders/unreal3.shs
  applications/sandbox/module/testModule.hpp
  applications/sandbox/source.cpp
  applications/sandbox/systems/gui_test.hpp
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystem.hpp
  applications/sandbox/systems/testsystemconvexhull.hpp
  legion/engine/core/containers/hashed_sparse_set.hpp
  legion/engine/core/containers/sparse_map.hpp
  legion/engine/core/core.vcxproj
  legion/engine/core/data/mesh.cpp
  legion/engine/core/ecs/entity_handle.hpp
  legion/engine/core/ecs/queryregistry.hpp
  legion/engine/core/scheduling/scheduler.cpp
  legion/engine/rendering/components/camera.hpp
  legion/engine/rendering/components/particle_emitter.hpp
  legion/engine/rendering/data/material.cpp
  legion/engine/rendering/data/material.hpp
  legion/engine/rendering/data/postprocessingeffect.hpp
  legion/engine/rendering/data/screen_quad.hpp
  legion/engine/rendering/data/shader.cpp
  legion/engine/rendering/data/shader.hpp
  legion/engine/rendering/data/texture.cpp
  legion/engine/rendering/data/texture.hpp
  legion/engine/rendering/pipeline/base/pipeline.inl
  legion/engine/rendering/pipeline/base/renderstage.hpp
  legion/engine/rendering/pipeline/default/defaultpipeline.cpp
  legion/engine/rendering/pipeline/default/postfx/tonemapping.cpp
  legion/engine/rendering/pipeline/default/postfx/tonemapping.hpp
  legion/engine/rendering/pipeline/default/stages/framebufferresizestage.cpp
  legion/engine/rendering/pipeline/default/stages/lightbufferstage.cpp
  legion/engine/rendering/pipeline/default/stages/lightbufferstage.hpp
  legion/engine/rendering/pipeline/default/stages/meshbatchingstage.cpp
  legion/engine/rendering/pipeline/default/stages/meshbatchingstage.hpp
  legion/engine/rendering/pipeline/default/stages/meshrenderstage.cpp
  legion/engine/rendering/pipeline/default/stages/postprocessingstage.cpp
  legion/engine/rendering/pipeline/default/stages/postprocessingstage.hpp
  legion/engine/rendering/pipeline/default/stages/submitstage.cpp
  legion/engine/rendering/pipeline/gui/stages/imguirenderstage.cpp
  legion/engine/rendering/pipeline/gui/stages/imguirenderstage.hpp
  legion/engine/rendering/rendering.hpp
  legion/engine/rendering/rendering.vcxproj
  legion/engine/rendering/rendering.vcxproj.filters
  legion/engine/rendering/systems/renderer.cpp
  legion/engine/rendering/util/bindings.hpp
Labels: bug, team rendering

#260 fix shaders
  applications/sandbox/assets/shaders/color.shs
  applications/sandbox/assets/shaders/debug.shs
  applications/sandbox/assets/shaders/groundplane.shs
  applications/sandbox/assets/shaders/normal.shs
  applications/sandbox/assets/shaders/position.shs
  applications/sandbox/assets/shaders/texture.shs
  applications/sandbox/assets/shaders/uv.shs
  applications/sandbox/assets/shaders/vertexcolor.shs
  applications/sandbox/assets/shaders/wireframe.shs
  applications/sandbox/assets/shaders/worldnormal.shs
  applications/sandbox/assets/shaders/worldposition.shs
  applications/sandbox/engine/shaders/invalid.shs
Labels: bug, team rendering

#262 Add readme feature list
  README.md
Labels: documentation

#264 FXAA
  applications/sandbox/engine/shaders/fxaa.shs
  applications/sandbox/source.cpp
  legion/engine/rendering/pipeline/default/defaultpipeline.cpp
  legion/engine/rendering/pipeline/default/postfx/fxaa.cpp
  legion/engine/rendering/pipeline/default/postfx/fxaa.hpp
  legion/engine/rendering/pipeline/default/postfx/tonemapping.cpp
  legion/engine/rendering/pipeline/default/stages/submitstage.cpp
  legion/engine/rendering/rendering.vcxproj
  legion/engine/rendering/rendering.vcxproj.filters
Labels: enhancement, team rendering

#266 fix logging for release
  legion/engine/core/engine/engine.hpp
  legion/engine/core/logging/logging.cpp
  legion/engine/core/logging/logging.hpp
Labels: bug

#267 Makeshift debug render stage (more to come later after the holidays but Priatama needs this asap)
  legion/editor/editor-application/editor-application.vcxproj
  legion/editor/editor-audio/editor-audio.vcxproj
  legion/editor/editor-core/editor-core.vcxproj
  legion/editor/editor-networking/editor-networking.vcxproj
  legion/editor/editor-physics/editor-physics.vcxproj
  legion/editor/editor-rendering/editor-rendering.vcxproj
  legion/editor/editor-scripting/editor-scripting.vcxproj
  legion/engine/application/application.vcxproj
  legion/engine/application/window/windowsystem.cpp
  legion/engine/audio/audio.vcxproj
  legion/engine/core/core.vcxproj
  legion/engine/core/core.vcxproj.filters
  legion/engine/core/engine/engine.hpp
  legion/engine/core/events/eventbus.hpp
  legion/engine/core/platform/platform.hpp
  legion/engine/networking/networking.vcxproj
  legion/engine/physics/physics.vcxproj
  legion/engine/rendering/data/shader.cpp
  legion/engine/rendering/debugrendering.hpp
  legion/engine/rendering/pipeline/default/defaultpipeline.cpp
  legion/engine/rendering/pipeline/default/stages/debugrenderstage.cpp
  legion/engine/rendering/pipeline/default/stages/debugrenderstage.hpp
  legion/engine/rendering/rendering.vcxproj
  legion/engine/rendering/rendering.vcxproj.filters
  legion/engine/rendering/systems/renderer.cpp
  legion/engine/rendering/systems/renderer.hpp
  legion/engine/scripting/scripting.vcxproj
Labels: enhancement, team rendering
