Repository Rythe-Interactive/Rythe-Engine, pull requests merged in 2020-11, with the labels that each got.

#183 added support for compute::Buffer in compute::function
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/systems/testsystem.hpp
  legion/engine/core/compute/buffer.hpp
  legion/engine/core/compute/context.hpp
  legion/engine/core/compute/high_level/function.cpp
  legion/engine/core/compute/high_level/function.hpp
  legion/engine/core/compute/kernel.cpp
  legion/engine/core/compute/kernel.hpp
  legion/engine/core/types/meta.hpp
  legion/engine/scripting/systems/delete_this
Labels: enhancement, team core

#185 fix issues with exiting engine
  legion/engine/core/async/readonly_rw_spinlock.cpp
  legion/engine/core/async/readonly_rw_spinlock.hpp
  legion/engine/core/scheduling/processchain.cpp
Labels: HIGH PRIORITY, bug, team core

#189 Create README.MD
  legion/engine/core/compute/README.MD
Labels: documentation

#193 fix missing linker folder
  applications/sandbox/sandbox.vcxproj
Labels: bug

#182 Warm starting Framework and minor bug fixes
  applications/sandbox/module/testModule.hpp
  applications/sandbox/systems/testsystem.hpp
  include/physics/colliders/convexcollider.hpp
  include/physics/colliders/physicscollider.hpp
  include/physics/components/physics_component.hpp
  include/physics/components/rigidbody.hpp
  include/physics/data/contact_vertex.hpp
  include/physics/data/convergance_identifier.hpp
  include/physics/data/convex_convergance_identifier.hpp
  include/physics/data/convexconvexpenetrationquery.hpp
  include/physics/data/edge_label.hpp
  include/physics/data/edgepenetrationquery.hpp
  include/physics/data/penetrationquery.h
  include/physics/halfedgeedge.hpp
  include/physics/halfedgeface.hpp
  include/physics/physics_contact.hpp
  include/physics/physics_statics.hpp
  include/physics/physicsconstants.hpp
  include/physics/systems/physicssystem.hpp
  legion/engine/physics/HalfEdgeFace.cpp
  legion/engine/physics/colliders/convexcollider.cpp
  legion/engine/physics/colliders/convexcollider.hpp
  legion/engine/physics/colliders/physicscollider.hpp
  legion/engine/physics/components/physics_component.hpp
  legion/engine/physics/components/rigidbody.hpp
  legion/engine/physics/data/contact_vertex.hpp
  legion/engine/physics/data/convergance_identifier.hpp
  legion/engine/physics/data/convex_convergance_identifier.hpp
  legion/engine/physics/data/convexconvexpenetrationquery.cpp
  legion/engine/physics/data/convexconvexpenetrationquery.hpp
  legion/engine/physics/data/edge_label.hpp
  legion/engine/physics/data/edgepenetrationquery.cpp
  legion/engine/physics/data/edgepenetrationquery.hpp
  legion/engine/physics/data/penetrationquery.h
  legion/engine/physics/halfedgeedge.hpp
  legion/engine/physics/halfedgeface.hpp
  legion/engine/physics/physics.vcxproj
  legion/engine/physics/physics.vcxproj.filters
  legion/engine/physics/physics_contact.hpp
  legion/engine/physics/physics_statics.hpp
  legion/engine/physics/physicsconstants.hpp
  legion/engine/physics/systems/physicssystem.cpp
  legion/engine/physics/systems/physicssystem.hpp
Labels: enhancement

#199 Fix typehash and make it run on release
  include/core/types/type_util.hpp
  legion/engine/core/types/type_util.hpp
Labels: bug

#198 vertex colors, parallex occlusion culling LOD, fix angles of spot lights
  applications/sandbox/assets/models/audio-source.mtl
  applications/sandbox/assets/models/audio-source.obj
  applications/sandbox/assets/models/xyz.mtl
  applications/sandbox/assets/models/xyz.obj
  applications/sandbox/assets/scenes/Main.cornflake
  applications/sandbox/assets/shaders/vertexcolor.shs
  applications/sandbox/engine/shaderlib/lighting.shinc
  applications/sandbox/engine/shaderlib/stdio.shinc
  applications/sandbox/engine/shaderlib/texturemaps.shinc
  applications/sandbox/systems/testsystem.hpp
  include/core/data/mesh.hpp
  include/core/math/color.hpp
  include/rendering/data/model.hpp
  include/rendering/util/bindings.hpp
  legion/engine/core/data/importers/mesh_importers.cpp
  legion/engine/core/data/mesh.cpp
  legion/engine/core/data/mesh.hpp
  legion/engine/core/math/color.hpp
  legion/engine/rendering/data/model.cpp
  legion/engine/rendering/data/model.hpp
  legion/engine/rendering/util/bindings.hpp
Labels: enhancement, team rendering

#218 Axis accumulation
  .gitignore
  legion/engine/application/events/inputevents.hpp
  legion/engine/application/input/inputmap.hpp
  legion/engine/application/input/inputsystem.cpp
  legion/engine/application/input/inputsystem.hpp
  legion/engine/core/engine/system.hpp
  legion/engine/core/events/eventbus.hpp
  legion/engine/core/scheduling/process.hpp
Labels: enhancement, team application/input

#220 fix POM, fix normal maps, shader error line numbers, optimize shaders
  applications/sandbox/assets/models/wizardgnomeretop.mtl
  applications/sandbox/assets/models/wizardgnomeretop.obj
  applications/sandbox/assets/models/xyz.obj
  applications/sandbox/assets/scenes/Main.cornflake
  applications/sandbox/assets/shaders/pbr.shs
  applications/sandbox/assets/shaders/skybox.shs
  applications/sandbox/assets/textures/test/test-normalHeight.png
  applications/sandbox/assets/textures/warlock/retopo_and_uv_warlock_5_Warlock_AO.tif
  applications/sandbox/assets/textures/warlock/retopo_and_uv_warlock_5_Warlock_BaseColor.tif
  applications/sandbox/assets/textures/warlock/retopo_and_uv_warlock_5_Warlock_Height.tif
  applications/sandbox/assets/textures/warlock/retopo_and_uv_warlock_5_Warlock_Metalness.tif
  applications/sandbox/assets/textures/warlock/retopo_and_uv_warlock_5_Warlock_Normal.tif
  applications/sandbox/assets/textures/warlock/retopo_and_uv_warlock_5_Warlock_Roughness.tif
  applications/sandbox/assets/textures/warlock/warlock-MRDAo.png
  applications/sandbox/assets/textures/warlock/warlock-albedo.png
  applications/sandbox/assets/textures/warlock/warlock-emissive.png
  applications/sandbox/assets/textures/warlock/warlock-height.png
  applications/sandbox/assets/textures/warlock/warlock-height2.png
  applications/sandbox/assets/textures/warlock/warlock-normalHeight.png
  applications/sandbox/assets/textures/warlock/warlock-smoothness.png
  applications/sandbox/engine/resources/default/MRDAo
  applications/sandbox/engine/resources/default/MRDAo.png
  applications/sandbox/engine/resources/default/Thumbs.db
  applications/sandbox/engine/resources/default/heighttemp.png
  applications/sandbox/engine/resources/default/normal
  applications/sandbox/engine/resources/default/normal2.png
  applications/sandbox/engine/resources/default/normalHeight
  applications/sandbox/engine/resources/default/normalHeight.png
  applications/sandbox/engine/resources/default/roughness.png
  applications/sandbox/engine/resources/default/smoothness.png
  applications/sandbox/engine/shaderlib/color_correction.shinc
  applications/sandbox/engine/shaderlib/lighting.shinc
  applications/sandbox/engine/shaderlib/lighting_input.shinc
  applications/sandbox/engine/shaderlib/math_ext.shinc
  applications/sandbox/engine/shaderlib/stdio.shinc
  applications/sandbox/engine/shaderlib/texturemaps.shinc
  applications/sandbox/module/testModule.hpp
  applications/sandbox/sandbox.vcxproj
  applications/sandbox/source.cpp
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/sandbox/systems/testsystem.hpp
  deps/include/tiny_obj_loader.h
  legion/engine/core/common/string_extra.hpp
  legion/engine/core/data/importers/mesh_importers.cpp
  legion/engine/core/entry/entry_point.hpp
  legion/engine/core/scheduling/processchain.cpp
  legion/engine/core/scheduling/scheduler.cpp
  legion/engine/rendering/data/model.cpp
  legion/engine/rendering/data/shader.cpp
Labels: enhancement
