Repository Rythe-Interactive/Rythe-Engine, pull requests merged in 2022-02, with the labels that each got.

#392 fix asset cache create
  legion/engine/core/assets/assetcache.hpp
  legion/engine/core/assets/assets.inl
Labels: bug

#394 Task/rework startup and shutdown
  applications/sandbox/systems/simplecameracontroller.hpp
  applications/unit_tests/source.cpp
  applications/unit_tests/tests/core/ecs.hpp
  applications/unit_tests/unit_test.hpp
  legion/engine/core/async/async.hpp
  legion/engine/core/async/lock_guard.hpp
  legion/engine/core/compute/context.cpp
  legion/engine/core/compute/context.hpp
  legion/engine/core/containers/sparse_map.hpp
  legion/engine/core/core.vcxproj
  legion/engine/core/core.vcxproj.filters
  legion/engine/core/defaults/coremodule.hpp
  legion/engine/core/ecs/containers/component_pool.hpp
  legion/engine/core/ecs/containers/component_pool.inl
  legion/engine/core/ecs/data/component_type.hpp
  legion/engine/core/ecs/filters/filterregistry.hpp
  legion/engine/core/ecs/filters/filterregistry.inl
  legion/engine/core/ecs/handles/entity.inl
  legion/engine/core/ecs/handles/filter.inl
  legion/engine/core/ecs/registry.cpp
  legion/engine/core/ecs/registry.hpp
  legion/engine/core/ecs/registry.inl
  legion/engine/core/engine/engine.cpp
  legion/engine/core/engine/engine.hpp
  legion/engine/core/engine/engine.inl
  legion/engine/core/engine/enginesubsystem.hpp
  legion/engine/core/entry/entry_point.hpp
  legion/engine/core/events/eventbus.hpp
  legion/engine/core/logging/logging.hpp
  legion/engine/core/scheduling/clock.hpp
  legion/engine/core/scheduling/scheduler.cpp
  legion/engine/core/scheduling/scheduler.hpp
  legion/engine/core/types/type_util.hpp
  tools/cppcheck2github.py
Labels: enhancement, team core

#396 Fixed a minor type mismatch for correctness' sake
  legion/engine/core/types/type_util.hpp
Labels: enhancement

#398 fixed import_settings::detectComponents being used incorrectly
  legion/engine/core/data/loaders/stbimageloader.cpp
Labels: enhancement

#403 fix debug renderer not clearing last line
  legion/engine/rendering/pipeline/default/stages/debugrenderstage.cpp
Labels: bug, team rendering
